services:
  fastapi:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 4 
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped